char *erlst[] = {
	"OK",
	"illegal line number",
	"illegal format specification",
	"illegal arithmetic expression",
	"ambiguous command",
	"illegal delimiter",
	"attempt to divide by zero",
	"working area full",
	"nonexistent name",
	"wrong variable type",
	"resources exhausted",
	"command not properly terminated",
	"unallocated error ?",
	"nonexistent line addressed",
	"illegal shuffle attempted",
	"error in IF command",
	"escape typed",
	"illegal EDIT command",
	"illegal ASK command",
	"error in ERASE command",
	"argument list error",
	"file error",
	"error in SAVE command",
	"array dimension error",
	"square root of neg.number",
	"illegal ARCtangent argument(s)",
	"sin() argument too big",
	"cosine() argument too big",
	"power error : negative argument or 0^0",
	"power underflow",
	"EXPONENTIAL argument too big",
	"LOGARITHM argument <= 0",
	"device not connected",
	"unauthorised action",
	"hardware error",
	"illegal equipment number",
	"illegal property",
	"value out of range",
	"not implemented yet",
	"no such computer",
	"result string filled",
	"syntax error",
	"no such file",
	"File already exists",
	"No file space",
	"Communication error",
	"remitted data lost",
	"end of file",
	"equipment error",
	"SIOM error (ND error)",
	"illegal error number",
	"checksum error",
	"Defined function area full",
	"Syntax error in DEFINE command",
	"illegal $SET command",
	"String Function failure",
	"illegal concatenation",
	"Error in $IF command",
	"Error in $ASK command",
	"String expected",
	"Pattern too BIG",
	"Bad Pattern Match",
	"Bad Pattern",
	"Bad Pattern Assignment",            /* 64 = 0..63  */
	"software not loaded",
	"failure in datalink software",
	"code failure",
	"bracket missing",
	"wrong hexadecimal number",
	"wrong octal number",
	"illegal character",
	"illegal relational operator",
	"command not allowed here",
	"illegal read/write attempted",
	"out of memory",
	"database not loaded",
	"illegal command",
	"resources exhausted",
	"file not open",
	"Camac error",
	"no serial camac loop",              /*1..3*/
	"simatic error",
	"driver not installed",
	"COMx port_not_available",
	"Scanner error",
	"High Voltage not detected",
	"Non existent Element",
	"Non existent Fec",
	"Non existent Client",
	"Unable to lock the memory",
	"Server not responding",
	"DDE Message not posted",
	"DDE Message not accepted from server",
	"DDE Timeout occured",
	"Illegal network protocol",
	"GPIB Hardware error",
	"RS232 Hardware error",
	"Fug in Transition",
	"Connection Timeout",
	"Illegal Mode",
	"Illegal PLS Line",
	"Undefined",
	"Network write error",
	"Invalid data",
	"Refreshperiod too high (min 2s)",
	"Access denied",
	"RPCserver busy",
	"Access to FEC disabled",
	"No response from FEC",
	"Illegal data type",
	"Profibus DP access error",
	""};