//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MCP for NT.rc
//
#define IDD_ABOUTBOX                    100
#define CG_ID_VIEW_MYDIALOGBAR          103
#define IDP_SOCKETS_INIT_FAILED         104
#define CG_ID_VIEW_LIST                 106
#define IDD_PROPPAGE_MEDIUM             106
#define CG_IDD_SAVEDIALOG               107
#define CG_ID_VIEW_SAVEDIALOG           108
#define CG_IDR_POPUP_MCPFOR_NTVIEW      109
#define CG_IDS_CANNOT_OPEN_CLIPBOARD    110
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA 111
#define CG_IDS_PHYSICAL_MEM             112
#define CG_IDS_DISK_SPACE               113
#define CG_IDS_DISK_SPACE_UNAVAIL       114
#define CG_IDS_DISK_SPACE_UNAVAIL2      115
#define CG_ID_VIEW_LOADFILEBAR          116
#define IDB_SPLASH                      117
#define CG_IDR_POPUP_DATA_CHILD         118
#define CG_ID_VIEW_DATASTYLE            120
#define CG_ID_VIEW_ERRORBAR             122
#define CG_ID_VIEW_LOAD                 124
#define ID_INDICATOR_DATE               125
#define ID_INDICATOR_TIME               126
#define CG_IDR_POPUP_EDITOR_VIEW        127
#define IDR_MAINFRAME                   128
#define IDR_MCPTYPE                     129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDI_ICON3                       132
#define IDI_ICON4                       133
#define CG_IDS_CANNOT_OPEN_CLIPBOARD1   134
#define CG_IDS_CANNOT_GET_CLIPBOARD_DATA1 135
#define IDR_TOOLBAR1                    136
#define CG_IDD_GPS_HTMEAS               137
#define CG_ID_VIEW_GPS_HTMEAS           138
#define CG_IDD_ISOLDEPROTONS            139
#define IDI_ICON5                       140
#define IDI_ICON6                       141
#define CG_ID_VIEW_ISOLDEPROTONS        142
#define IDB_BITMAP1                     143
#define IDD_PAGE1RS                     148
#define IDD_PAGE2RS                     149
#define IDD_PAGE3RS                     150
#define IDD_PAGE1HP                     151
#define IDD_PAGE2HP                     152
#define IDD_PAGE3HP                     153
#define IDD_PAGE1HV                     154
#define IDI_ICON10                      154
#define IDD_PAGE2HV                     155
#define IDI_ICON11                      155
#define IDD_PAGE3HV                     156
#define IDD_PAGE1AM                     157
#define IDI_ICON13                      158
#define IDD_PAGE2AM                     158
#define IDI_ICON7                       159
#define IDD_PAGE3AM                     159
#define IDI_ICON8                       160
#define IDD_PAGE1FS                     160
#define IDD_PAGE2FS                     161
#define IDD_PAGE3FS                     162
#define IDD_PAGE1MS                     163
#define IDC_CURSOR1                     163
#define IDD_PAGE2MS                     164
#define IDD_PAGE3MS                     165
#define IDR_ACCELERATOR1                166
#define IDD_MEASTHREAD                  168
#define ID_TEMPLATEPANE                 169
#define IDR_MAINFRAME_TOOLBAR1          170
#define IDD_TEMPLATECALCUL              172
#define IDD_MINUIT                      173
#define IDD_DATAREADOUT                 174
#define IDD_HFSFIT                      179
#define IDD_RECHNER                     180
#define IDD_CONFIGURE                   182
#define IDD_SETUP                       183
#define IDD_CAMACSEND                   185
#define IDD_HARDWARE                    187
#define IDI_ICON9                       190
#define IDI_ICON12                      191
#define IDB_BITMAP2                     195
#define IDI_ICON14                      201
#define IDI_ICON15                      202
#define IDR_TOOLBAR2                    206
#define IDR_MENU1                       208
#define IDR_TOOLBAR3                    209
#define IDR_TOOLBAR4                    211
#define IDB_BITMAP3                     212
#define IDR_TOOLBAR5                    213
#define IDB_BITMAP4                     214
#define IDB_BITMAP5                     218
#define IDC_DEVICE_TOOLBAR_COMBO        219
#define IDB_BITMAP6                     221
#define IDB_BITMAP7                     222
#define IDB_BITMAP8                     223
#define IDB_BITMAP9                     224
#define CG_IDD_LOADFILEBAR              315
#define IDD_PAGE1PM                     316
#define IDD_PAGE3PM                     317
#define IDD_PAGE2PM                     318
#define IDD_PAGE1MF                     319
#define IDD_PAGE2MF                     320
#define IDD_PAGE3MF                     321
#define IDD_PAGE1FD                     322
#define IDD_PAGE2FD                     323
#define IDD_PAGE3FD                     324
#define IDD_PAGE1AS                     325
#define IDD_PAGE2AS                     326
#define IDD_PAGE3AS                     327
#define IDD_STEPTIMER                   328
#define IDD_FASTTIMER                   329
#define IDD_TIMER                       330
#define IDD_COMPUTER                    331
#define IDD_TRIGGERPART                 332
#define IDD_PAGE1TI                     333
#define IDD_PAGE3TI                     334
#define IDD_PAGE1TR                     335
#define IDD_PAGE3TR                     336
#define IDD_NETREAD                     337
#define IDD_PAGE1PR                     338
#define IDD_PAGE3PR                     339
#define IDD_PAGE1BO                     340
#define IDD_PAGE3BO                     341
#define IDD_PAGE1FV                     342
#define IDD_PAGE3FV                     343
#define IDD_GPIBWRITE                   344
#define IDD_PAGE2FV                     345
#define IDD_GPIBREAD                    346
#define IDD_PAGE1FR                     347
#define IDD_PAGE1FW                     348
#define IDD_PAGE1GR                     349
#define IDD_PAGE1KW                     350
#define IDD_PAGE1GW                     351
#define IDD_PAGE1KR                     352
#define IDD_PAGE3FR                     353
#define IDD_PAGE3FW                     354
#define IDD_PAGE3GR                     355
#define IDD_PAGE3GW                     356
#define IDD_PAGE3KR                     357
#define IDD_PAGE3KW                     358
#define IDD_NETWRITE                    359
#define IDD_PAGE1LV                     360
#define IDD_PAGE2LV                     361
#define IDD_PAGE3LV                     362
#define IDD_SICLREAD                    363
#define IDD_PAGE1SR                     364
#define IDD_PAGE3SR                     365
#define IDC_EDIT1                       1003
#define IDC_ACTPOS                      1003
#define IDC_PROTONLIMIT                 1003
#define IDC_NUMOFPEAKS                  1003
#define IDC_SUBADDRESS                  1004
#define IDC_EDIT2                       1004
#define IDC_DONEPOS                     1004
#define IDC_LINEWIDTH                   1004
#define IDC_PHYSICAL_MEM                1005
#define IDC_EDIT3                       1005
#define IDC_LEFTPOS                     1005
#define IDC_TIMELEFT                    1005
#define IDC_ACCELVOLTAGE                1005
#define IDC_DISK_SPACE                  1006
#define IDC_FIT_RED                     1006
#define IDC_F                           1006
#define IDC_PRESETSLOT                  1006
#define IDC_FIT_GREEN                   1007
#define IDC_LISTSLOT                    1007
#define IDC_FIT_BLUE                    1008
#define IDC_PREMASLOT                   1008
#define IDC_AXIS_RED                    1009
#define IDC_GELBEBOXSLOT                1009
#define IDC_AXIS_GREEN                  1010
#define IDC_PROTONSUBADD                1010
#define IDC_AXIS_BLUE                   1011
#define IDC_TRIGGERSUBADD               1011
#define IDC_TEXT_RED                    1012
#define IDC_FERDDICHSUBADD              1012
#define IDC_TEXT_GREEN                  1013
#define IDC_HP1GPIB                     1013
#define IDC_TEXT_BLUE                   1014
#define IDC_HP2GPIB                     1014
#define IDC_FITFUNRES                   1015
#define IDC_RS1GPIB                     1015
#define IDC_SELECT_RED                  1016
#define IDC_RS2GPIB                     1016
#define IDC_STARTFREQ                   1017
#define IDC_SELECT_GREEN                1017
#define IDC_FLUKEGPIB                   1017
#define IDC_STOPFREQ                    1018
#define IDC_SELECT_BLUE                 1018
#define IDC_HPVOLTSLOT                  1018
#define IDC_STEPFREQ                    1019
#define IDC_NUMBER_RED                  1019
#define IDC_PREMADELAY                  1019
#define IDC_CENTERFREQ                  1020
#define IDC_NUMBER_GREEN                1020
#define IDC_MASSDELAY                   1020
#define IDC_AMPDB                       1021
#define IDC_NUMBER_BLUE                 1021
#define IDC_FLUKEDELAY                  1021
#define IDC_AMPMV                       1022
#define IDC_TEMPLATE_Y                  1022
#define IDC_GPIBDELAY                   1022
#define IDC_STARTVOLT                   1023
#define IDC_SCRIPT_Y                    1023
#define IDC_FVOLTSLOT                   1023
#define IDC_STOPVOLT                    1024
#define IDC_BACK_RED                    1024
#define IDC_TEMPGPIB                    1024
#define IDC_STEPVOLT                    1025
#define IDC_BACK_GREEN                  1025
#define IDC_FIELDGPIB                   1025
#define IDC_CENTERVOLT                  1026
#define IDC_BACK_BLUE                   1026
#define IDC_GELBEBOX2SLOT               1026
#define IDC_SLOWRESET                   1027
#define IDC_PLOT_DX                     1027
#define IDC_HVVOLTSLOT                  1027
#define IDC_SLOWRESETCH                 1028
#define IDC_PLOT_X                      1028
#define IDC_DIP_HT                      1028
#define IDC_AMPOFF                      1029
#define IDC_PLOT_DY                     1029
#define IDC_DIP_PC                      1029
#define IDC_NOMOD                       1030
#define IDC_PLOT_Y                      1030
#define IDC_DIP_HT_VALUE                1030
#define IDC_MODAM                       1031
#define IDC_LSI_DX                      1031
#define IDC_DIP_PC_VALUE                1031
#define IDC_MODFM                       1032
#define IDC_LSI_X                       1032
#define IDC_SICLREADERSUBADD            1032
#define IDC_MODFREQ                     1033
#define IDC_LSI_DY                      1033
#define IDC_SICLREADERSUBADD2           1033
#define IDC_SICLSTEPSUBADD              1033
#define IDC_MODAMPAM                    1034
#define IDC_LSI_Y                       1034
#define IDC_PREMADELAY2                 1034
#define IDC_PREMAPOSTDELAY              1034
#define IDC_MODAMPFM                    1035
#define IDC_MONITOR_DX                  1035
#define IDC_SETFREQ                     1036
#define IDC_MONITOR_X                   1036
#define IDC_SETVOLT                     1037
#define IDC_MONITOR_DY                  1037
#define IDC_NULLVOLT                    1038
#define IDC_MONITOR_Y                   1038
#define IDC_GPIB                        1039
#define IDC_TEST                        1040
#define IDC_SENDCOMMAND                 1041
#define IDC_SLOT                        1042
#define IDC_TEST2                       1043
#define IDC_RADIO1                      1043
#define IDC_REWIND                      1043
#define IDC_GPS                         1043
#define IDC_POINTS                      1043
#define IDC_NOTRIGGER                   1043
#define IDC_GAUSS                       1043
#define IDC_DELAY                       1043
#define IDC_18BITINTERNAL               1043
#define IDC_RADIO2                      1044
#define IDC_HRS                         1044
#define IDC_STAIRS                      1044
#define IDC_STEPTRIGGER                 1044
#define IDC_LORENTZ                     1044
#define IDC_24BITOPTICAL                1044
#define IDC_RADIO3                      1045
#define IDC_LINES                       1045
#define IDC_SWEEPTRIGGER                1045
#define IDC_VOIGT                       1045
#define IDC_RADIO4                      1046
#define IDC_SAVEEDIT                    1046
#define IDC_REDOSTOP                    1046
#define IDC_DECAY                       1046
#define IDC_GAUSSEXP                    1046
#define IDC_LORENTZEXP                  1047
#define IDC_VOIGTEXP                    1048
#define IDC_NOFLUKE                     1049
#define IDC_FLUKE1                      1050
#define IDC_FLUKE2                      1051
#define IDC_FLUKE3                      1052
#define IDC_MOVECM                      1053
#define IDC_USEBRAKE                    1054
#define IDC_SETAMU                      1055
#define IDC_AUTORESIZE                  1055
#define IDC_MOVETO                      1056
#define IDC_SUMVOLTAGE                  1056
#define IDC_SETAMU2                     1056
#define IDC_AUTOOPEN                    1058
#define IDC_DATAOP                      1059
#define IDC_ERROROP                     1060
#define IDC_PROGTRACK                   1061
#define IDC_PROGSTEP                    1062
#define IDC_PROGSCAN                    1063
#define IDC_NOREDO                      1064
#define IDC_REDOWAIT                    1065
#define IDC_REDOWAITREDO                1066
#define IDC_FILELIST                    1067
#define IDC_ADDLIST                     1068
#define IDC_SUB                         1069
#define IDC_ADD                         1070
#define IDC_TEMPLVIEW                   1071
#define IDC_ADDBUTSUBSTRACT             1072
#define IDC_SAVEADDED                   1074
#define IDC_ISOTOPENAME                 1075
#define IDC_NUMSCANS                    1076
#define IDC_NUMSTEPS                    1077
#define IDC_REALSCANS                   1078
#define IDC_NOMASS                      1079
#define IDC_ELEMENTNAME                 1079
#define IDC_OPENBEAMGATE                1080
#define IDC_WAVENUMBER                  1080
#define IDC_OPENSCALER                  1081
#define IDC_CYCLES                      1081
#define IDC_CLOSEBEAMGATE               1082
#define IDC_KEPCOFACTOR                 1082
#define IDC_CLOSESCALER                 1083
#define IDC_BASEOFFSET                  1084
#define IDC_STARTBEAMGATE               1084
#define IDC_LINOFFSET                   1085
#define IDC_STOPBEAMGATE                1085
#define IDC_NEGATIVEPEAKS               1086
#define IDC_EQUALSPACED                 1087
#define IDC_BUTTON1                     1088
#define IDC_CENTERINSWEEP               1088
#define IDC_EVALUATE                    1088
#define IDC_SHOWPROTONS                 1088
#define IDC_SENDNAF                     1088
#define IDC_COMMONWIDTH                 1088
#define IDC_ACTSTEP                     1089
#define IDC_ACTTRACK                    1090
#define IDC_ACTSCAN                     1091
#define IDC_STEP                        1092
#define IDC_TRACK                       1093
#define IDC_SCAN                        1094
#define IDC_TEXTX                       1095
#define IDC_ACTCYCLE                    1095
#define IDC_NUMERR                      1096
#define IDC_CYCLE                       1096
#define IDC_TEXTERR                     1097
#define IDC_NUMX                        1098
#define IDC_NUMY                        1099
#define IDC_TEXTY                       1100
#define IDC_LINEAR                      1103
#define IDC_HFSFIT                      1105
#define IDC_EDIT4                       1106
#define IDKILL                          1106
#define IDC_MASS                        1106
#define IDC_USERFIT                     1106
#define IDC_EDIT5                       1107
#define IDC_ERGEBNIS                    1107
#define IDC_J_G                         1107
#define ID_HALTMEAS                     1107
#define IDC_GAUSS_EXP                   1107
#define IDC_EDIT6                       1108
#define IDC_J_A                         1108
#define IDC_LORENTZ_EXP                 1108
#define IDC_EDIT7                       1109
#define IDC_I                           1109
#define IDC_VOIGT_EXP                   1109
#define IDC_EDIT8                       1110
#define IDC_ISV                         1110
#define IDC_COS_EXP                     1110
#define IDC_EDIT9                       1111
#define IDC_A_G                         1111
#define IDC_EDIT10                      1112
#define IDC_B_G                         1112
#define IDC_EDIT11                      1113
#define IDC_A_A                         1113
#define IDC_EDIT12                      1114
#define IDC_B_A                         1114
#define IDC_TITLEPOSY                   1115
#define IDC_KEPCO                       1115
#define IDC_XAXISTITLEX                 1116
#define IDC_XAXISTITLEY                 1117
#define IDC_YAXISTITLEX                 1118
#define IDC_YAXISTITLEY                 1119
#define IDC_TICKLABELSX                 1120
#define IDC_TICKLABELSY                 1121
#define IDC_DATAXMIN                    1122
#define IDC_DATAYMIN                    1123
#define IDC_DATAXMAX                    1124
#define IDC_DATAYMAX                    1125
#define IDC_TICKLENX                    1126
#define IDC_HALFTICKLENX                1127
#define IDC_TICKLENY                    1128
#define IDC_HALFTICKLENY                1129
#define IDC_AXISTEXT                    1130
#define IDC_NUMBERS                     1131
#define IDC_AXISLINES                   1132
#define IDC_TICKLINES                   1133
#define IDC_DATALINES                   1134
#define IDC_FITLINES                    1135
#define IDC_ERRORBARS                   1136
#define IDC_TITLEPOSX                   1137
#define IDC_DATA_RED                    1138
#define IDC_DATA_GREEN                  1139
#define IDC_DATA_BLUE                   1140
#define IDC_INFORM                      1141
#define IDC_TEMPLATE_DX                 1145
#define IDC_TEMPLATE_DY                 1146
#define IDC_TEMPLATE_X                  1147
#define IDC_SCRIPT_DX                   1148
#define IDC_SCRIPT_X                    1149
#define IDC_SCRIPT_DY                   1150
#define IDC_AUTOSCRIPT                  1151
#define IDC_AUTOLSI                     1152
#define IDC_INFO                        1152
#define IDC_AUTOTEMPLATE                1153
#define IDC_CAMACANSWER                 1153
#define IDC_AUTOPLOT                    1154
#define IDC_DATA                        1154
#define IDC_N                           1155
#define IDC_AUTOMONITOR                 1155
#define IDC_A                           1156
#define IDC_RANDOM                      1157
#define IDC_SCALERSLOT                  1160
#define IDC_PROTONSLOT                  1161
#define IDC_GPIBSLOT                    1162
#define IDC_WAVELENGTH                  1163
#define IDC_READNET                     1164
#define IDC_NAME                        1165
#define IDC_PROPERTY                    1166
#define IDC_GET_PROPERTY                1166
#define IDC_SET_PROPERTY                1166
#define IDC_NETANSWER                   1167
#define IDC_VALUE                       1167
#define IDC_GPS_HTMEAS                  1168
#define IDC_HTMEASICON                  1169
#define IDC_BITON                       1170
#define IDC_BITOFF                      1171
#define IDC_BITTOGGLE                   1172
#define IDC_BITCHANNEL                  1173
#define IDC_ADDRESS                     1174
#define IDC_WRITEGPIB                   1175
#define IDC_GPIBSTRING                  1176
#define IDC_GPIBANSWER                  1177
#define IDC_NOSCANFREQ                  1178
#define IDC_NOSCANAMPDB                 1179
#define IDC_NOSCANAMPMV                 1180
#define IDC_NOSCANAMPOFF                1181
#define IDC_NOSCANNOMOD                 1182
#define IDC_NOSCANMODAM                 1183
#define IDC_NOSCANMODFM                 1184
#define IDC_NOSCANMODFREQ               1185
#define IDC_NOSCANMODAMPAM              1186
#define IDC_NOSCANMODAMPFM              1187
#define IDC_NOSCANVOLT                  1188
#define IDC_FIELD                       1189
#define IDC_SENDSTRING                  1190
#define IDC_TEMP                        1191
#define IDC_PROTONICON                  1193
#define IDC_GPS_PROTONS                 1194
#define IDC_WRITENET                    1195
#define IDC_FORWARD                     1198
#define IDC_BACKWARDS                   1199
#define IDC_SICLSTRING                  1200
#define IDC_SICLANSWER                  1201
#define IDC_WRITESICL                   1202
#define IDC_SICL                        1203
#define ID_HTMEAS_ICON                  32870
#define ID_PROTONS_ICON                 32871
#define ID_DUMMY_LABEL                  32872
#define ID_HTMEAS                       32873
#define ID_PROTONS                      32874
#define ID_SAVEFILE                     32875
#define ID_LOADFILE                     32876
#define ID_NEW_SICLREADER               32877
#define ID_SICLREADER                   32878
#define ID_NEW_SICLREADERSTEP           32879
#define ID_SICLREADERSTEP               32880
#define ID_BUTTON32772                  38772
#define ID_BUTTON32773                  38773
#define ID_BUTTON32774                  38774
#define ID_BUTTON32775                  38775
#define ID_BUTTON32776                  38776
#define ID_BUTTON32777                  38777
#define ID_NEW_SCALER1                  38779
#define ID_POPUP_NEW_SCALER             38779
#define CG_ID_LOADFILEBAR               38782
#define ID_SAVESETTINGS                 38783
#define ID_POPUP_SHOWPROPERTIES         38784
#define ID_POPUP_NEW_ARITHSCALER        38792
#define ID_POPUP_NEW_RSDEKADE           38793
#define ID_POPUP_NEW_HPDEKADE           38794
#define ID_POPUP_NEW_HPDAC              38795
#define ID_POPUP_NEW_FDAC               38796
#define ID_POPUP_NEW_ISOLDEMASS         38797
#define ID_POPUP_NEW_FLUKESWITCH        38798
#define ID_POPUP_RESIZETOFULLSCALE      38800
#define ID_LASTCOMMAND                  38801
#define ID_NEXTCOMMAND                  38802
#define ID_SELECTCOMMAND                38803
#define ID_RETURN                       38804
#define ID_POPUP_NEW_TRACK              38805
#define ID_ERGO                         38806
#define ID_GO                           38807
#define ID_KILL                         38808
#define ID_POPUP_NEW_TRIGGER            38809
#define ID_POPUP_NEW_ALEXMOTOR          38810
#define ID_VIEW_TEMPLATECALCULATOR      38811
#define ID_LSIBOX                       38816
#define ID_POPUP_SAVESPEC               38817
#define ID_POPUP_MINUITFITSESSION       38818
#define ID_VIEW_SCRIPTWINDOW            38821
#define ID_POPUP_LOADSPEC               38822
#define ID_POPUP_LOAD                   38823
#define ID_POPUP_SAVE                   38824
#define ID_POPUP_CLEARWINDOW            38826
#define ID_VIEW_EMPTYPLOT               38829
#define ID_VIEW_DISPLAYSETUP            38830
#define ID_ACCEL32834                   38834
#define ID_POPUP_NEW_KEPKOVOLTAGE       38835
#define ID_ACCEL32837                   38837
#define ID_VIEW_CAMACTESTER             38838
#define ID_VIEW_HARDWARESETUP           38839
#define ID_POPUP_NEW_ISOLDEVOLTAGE      38840
#define ID_POPUP_NEW_PREMAVOLTAGE       38841
#define ID_POPUP_SAVEWMF                38842
#define ID_VIEW_NETREADER               38844
#define ID_CONFIGURE                    38846
#define ID_GPIBWRITER                   38847
#define ID_SETSCANRANGE                 38851
#define ID_GPIBREADER                   38852
#define ID_FIELDREADER                  38853
#define ID_OUTBIT                       38854
#define ID_TEMPREADER                   38855
#define ID_POPUP_GPIBWRITER             38856
#define ID_POPUP_FIELDWRITER            38857
#define ID_MENU_GPIBREADER              38858
#define ID_MENU_GPIBWRITER              38859
#define ID_TEMPWRITER                   38860
#define ID_RESET                        38861
#define ID_VIEW_NETWRITER               38862
#define ID_POPUP_NEW_HVDAC              38863
#define ID_AUTOGO                       38865
#define ID_BUTTON32866                  38866
#define ID_FILE_NEW_TB                  38867
#define ID_FILE_OPEN_TB                 38868
#define ID_FILE_SAVE_AS_TB              38869
#define ID_EDIT_CUT_TB                  38870
#define ID_EDIT_COPY_TB                 38871
#define ID_EDIT_PASTE_TB                38872
#define ID_FILE_PRINT_TB                38873
#define ID_VIEW_SICLREADER              38874
#define ID_APP_ABOUT_TB                 38875
#define ID_CONTEXT_HELP_TB              38876
#define ID_RESET_TB                     38877
#define ID_BUTTON32872                  38878
#define ID_FILE_SAVEOLD                 38879
#define ID_TEMPLATEDEFTEXT              61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           143
#endif
#endif
