//   The Object Names
#define _TrackObj					"Track" 
#define _HP_VoltageSweepObj			"HP_VoltageSweepObj"           // this are all successor-classes of ActionObj
#define _Line_VoltageSweepObj		"LineVoltageSweepObj"
#define _HP8660B_FrequencySweepObj  "HP8660B_FrequencySweepObj"
#define _HP3325B_FrequencySweepObj  "HP3325B_FrequencySweepObj"
#define _HP3325B2_FrequencySweepObj "HP3325B2_FrequencySweepObj"
#define _RS_FrequencySweepObj		"RS_FrequencySweepObj"
#define _RS2_FrequencySweepObj		"RS2_FrequencySweepObj"
#define _PM_SpectrumObj				"PM_SpectrumObj"
#define _PM_ArithObj				"PM_ArithObj"
#define _PremaVoltageObj			"PremaVoltageObj"
#define _FlukeVoltageObj			"FlukeVoltageObj"
#define _IsoldeNetVoltageObj		"IsoldeNetVoltageObj"
#define _SiclReaderObj				"SiclReaderObj"
#define _SiclStepObj				"SiclStepObj"
#define _KepcoEichungVoltageObj		"KepcoEichungVoltageObj"
#define _ComputerDelayObj			"ComputerDelayObj"
#define _TimerDelayObj				"TimerDelayObj"
#define _StepTimerDelayObj			"StepTimerDelayObj"
#define _FastTimerDelayObj			"FastTimerDelayObj"
#define _Keithley_VoltageMeasObj	"Keithley_VoltageMeasObj"
#define _FlukeOsziObj				"FlukeOsziObj"
#define _MassAndFlukeSwitchObj		"MassAndFlukeSwitchObj"
#define _MassSwitchObj				"MassSwitchObj"
#define _FlukeSwitchObj				"FlukeSwitchObj"
#define _TriggerSweepObj			"TriggerSweepObj"
#define _StepTriggerObj				"StepTriggerObj"
#define _TriggerPartSweepObj		"TriggerPartSweepObj"
#define _AlexMotorObj				"AlexMotorObj"
#define _MultiFunctionObj			"MultiFunctionObj"
#define _FDAC_VoltageSweepObj		"FDAC_VoltageSweepObj"
#define _CamacLPObj					"CamacLPObj"
#define _CCDCameraObj				"CCDCameraObj"
#define _DummyObj					"DummyObj"
#define _TriggerObj					"TriggerObj"

#define _GPIBReaderObj				"GPIBReaderObj"
#define _FieldReaderObj				"FieldReaderObj"
#define _TempReaderObj				"TempReaderObj"
#define _TempWriterObj				"TempWriterObj"
#define _OutBitObj					"OutBitObj"
#define _FieldWriterObj				"FieldWriterObj"
#define _GPIBWriterObj				"GPIBWriterObj"

//  The shown Names
#define __TrackObj						"Track" 
#define __HP_VoltageSweepObj			"HPVoltage" 
#define __Line_VoltageSweepObj			"LineVoltage"
#define __HP8660B_FrequencySweepObj		"HP8660Decade"
#define __HP3325B_FrequencySweepObj		"HP3325Decade"
#define __HP3325B2_FrequencySweepObj	"HP3325Decade 2"
#define __RS_FrequencySweepObj			"RSDecade"
#define __PM_SpectrumObj				"Scaler"
#define __PM_ArithObj	   				"ArithScaler"
#define __PremaVoltageObj				"PremaVoltage"
#define __FlukeVoltageObj				"FlukeVoltage"
#define __IsoldeNetVoltageObj			"IsolNetVoltage"
#define __SiclReaderObj					"SICLReader"
#define __SiclStepObj					"SICLStep"
#define __KepcoEichungVoltageObj		"KepcoEichung"
#define __ComputerDelayObj				"ComputerDelay"
#define __TimerDelayObj					"TimerDelay"
#define __StepTimerDelayObj				"StepTimerDelay"
#define __FastTimerDelayObj				"FastTimerDelay"
#define __Keithley_VoltageMeasObj		"KeithleyVoltage"
#define __FlukeOsziObj					"FlukeOszi"
#define __MassAndFlukeSwitchObj			"MassAndFluke"
#define __MassSwitchObj					"MassSwitch"
#define __FlukeSwitchObj				"FlukeSwitch"
#define __TriggerSweepObj				"TriggerSweep"
#define __StepTriggerObj				"StepTrigger"
#define __TriggerPartSweepObj			"TriggerPartSweep"
#define __AlexMotorObj					"AlexMotor"
#define __MultiFunctionObj				"MultiFunction"
#define __FDAC_VoltageSweepObj			"FVoltage"
#define __CamacLPObj					"CamacListProc"
#define __CCDCameraObj					"CCDCamera"
#define __DummyObj						"Dummy"
#define __TriggerObj					"Trigger"

#define __GPIBReaderObj					"GPIBReader"
#define __FieldReaderObj				"FieldReader"
#define __TempReaderObj					"TempReader"
#define __TempWriterObj					"TempWriter"
#define __OutBitObj						"OutBit"
#define __FieldWriterObj				"FieldWriter"
#define __GPIBWriterObj					"GPIBWriter"

#define GPS_HTMEAS		WM_USER + 1000
#define ISOLDE_PROTONS	WM_USER + 1001